### ISSUE TITLE
Batch review mods

### ISSUE THREAD

**Issue by smarsland** [smarsland/AviaNZ#31] opened 2019-09-02 21:18 UTC
(1) It would be nice to have the playbar draggable
(2) If a species name is not in the checkboxes, but in the list, then deselecting it doesn't stop it being listed. As well as fixing this:
(3) We should put all the bird names that are in the segments be in the check boxes
(4) It's probably not worth doing dynamic update on them, though
(5) There is still a text label bug (string or separate letters) when you add a species here

**Comment by jjuod** [comment] 2019-09-03 01:20
(1) discussed, but probably not. Will reopen separately
(2)-(4) fixed in  46da16f39068f490e67705a3c3802c4d70b1ae0f:
* birds in the label are always shown in the boxes and sorted to be at the start, left column, to avoid looking over 30 buttons for a tick
* if `ReorderList` interface option is *not* set, the boxes will return to their places for the next segment
* list box talks to the check boxes now, so the user can click either and both will update smoothly

(5) could not reproduce in manual mode, will check batch mode. But now the custom-bird box makes use of the shared handlers, so might be fixed in 46da16f39068f490e67705a3c3802c4d70b1ae0f

Unpredictable behavior may still result if:
* user has no Long Bird List
* user somehow got an annotation which is not in the Long Bird List

**Comment by jjuod** [comment] 2019-09-03 01:36
Could not reproduce (5). Closing unless anyone would notice it and provide an example file.

**Comment by jjuod** [comment] 2019-09-08 23:11
Reopening so that i'd remember to check the ReorderList problems in https://github.com/smarsland/AviaNZ/commit/bfa427a1635bfba4d07512fe801dd132cf3eafda

**Comment by jjuod** [comment] 2019-10-11 01:30
ReorderList now either allows full dynamics, or permanently freezes the list, in d7a4412

**Closed by jjuod** 2019-10-11 01:30 UTC
